# Generated by Django 5.2.8 on 2025-11-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
