# Generated by Django 5.2.8 on 2025-11-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code for ticket verification', null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open for Registration'), ('CLOSED', 'Closed'), ('PENDING', 'Pending Approval')], default='OPEN', max_length=10),
        ),
    ]
